# Generated by Django 5.1.5 on 2025-04-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_story_estimated_time_task_estimated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='xp',
        ),
    ]
