# Generated by Django 5.1.5 on 2025-05-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('task', 'Task'), ('story', 'Story'), ('checkin', 'Check-in')], max_length=10),
        ),
    ]
