# Generated by Django 5.1.5 on 2025-05-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_activity_points_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='points',
            new_name='reward',
        ),
    ]
