# Generated by Django 5.1.5 on 2025-05-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_rename_points_activity_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
