# Generated by Django 5.1.5 on 2025-06-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='story_banners/'),
        ),
        migrations.AddField(
            model_name='task',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='task_banners/'),
        ),
    ]
