# Generated by Django 5.1.5 on 2025-06-12 02:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_story_banner_task_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='task_banners/'),
        ),
    ]
