# Generated by Django 5.1.5 on 2025-06-12 04:12

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_task_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='story_banners/'),
        ),
    ]
