# Generated by Django 5.1.5 on 2025-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggle to activate/deactivate this giveaway'),
        ),
    ]
