# Generated by Django 5.1.5 on 2025-06-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_giveaway_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giveaway',
            options={'ordering': ['-created_at']},
        ),
    ]
