# Generated by Django 5.1.5 on 2025-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_alter_story_estimated_time_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
