# Generated by Django 5.1.5 on 2025-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_story_estimated_time_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='estimated_time',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(default=1),
        ),
    ]
