# Generated by Django 5.1.5 on 2025-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_story_estimated_time_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wait_for_confirm',
            field=models.BooleanField(default=False, help_text='If True, user must wait for admin confirmation (for riddles)'),
        ),
    ]
