# Generated by Django 5.1.5 on 2025-09-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_task_wait_for_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='wait_for_confirm',
        ),
        migrations.AddField(
            model_name='task',
            name='no_code_required',
            field=models.BooleanField(default=False, help_text="If True, task doesn't require confirmation code"),
        ),
        migrations.AddField(
            model_name='task',
            name='no_wait_confirm',
            field=models.BooleanField(default=False, help_text='If True, task can be confirmed without waiting for timer'),
        ),
    ]
