# Generated by Django 5.1.5 on 2025-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_remove_task_wait_for_confirm_task_no_code_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_riddle',
            field=models.BooleanField(default=False, help_text='If True, this is a riddle task (no timer, no link)'),
        ),
    ]
