# Generated by Django 5.1.5 on 2025-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_task_is_riddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
