# Generated by Django 5.1.5 on 2025-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
