# Generated by Django 5.1.5 on 2025-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', help_text='Unique transaction reference for traceability.', max_length=100, unique=True),
        ),
    ]
